name: Deploy Webhook

on:
  push:
    branches:
      - deploy

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hosting Webhook
        run: |
          curl -f -X POST "https://by4010.hb.by:8443/modules/git/public/web-hook.php?uuid=545844a5-6f56-2a7d-37aa-0a92eb58d127"
